version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: cp-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cognitive}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: cp-redis
    ports: ["6379:6379"]

  temporal:
    image: temporalio/auto-setup:1.25.1
    container_name: cp-temporal
    environment:
      - DB=sqlite
    ports: ["7233:7233"]

  temporal-ui:
    image: temporalio/ui:2.30.2
    container_name: cp-temporal-ui
    environment:
      - TEMPORAL_ADDRESS=cp-temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports: ["8080:8080"]
    depends_on:
      - temporal

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: cp-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.103.1
    container_name: cp-otel
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel-collector.yaml:ro
    depends_on:
      - jaeger
    ports:
      - "4317:4317"
      - "4318:4318"

volumes:
  pgdata:
