version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: enterprise-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: enterprise-app
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - enterprise-network

  redis:
    image: redis:7.2-alpine
    container_name: enterprise-redis
    restart: unless-stopped
    networks:
      - enterprise-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: enterprise-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/enterprise-app?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRE: 7d
      LOG_LEVEL: info
      REDIS_URL: redis://redis:6379
    volumes:
      - ./server/logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - enterprise-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: enterprise-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - enterprise-network

volumes:
  mongodb_data:

networks:
  enterprise-network:
    driver: bridge
