[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olympus-llm"
version = "0.1.0"
description = "Local-first LLM router with cloud fallback"
requires-python = ">=3.10"
dependencies = ["httpx>=0.27.0"]

[tool.setuptools]
packages = ["olympus_llm"]
