[project]
name = "retrieval-service"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.0",
  "asyncpg>=0.29.0",
  "pydantic>=2.7.0",
  "olympus-api @ file://../apps/api"
]