[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olympus-automation"
version = "0.1.0"
description = "Automation drivers and artifact logging"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = ["olympus_automation"]
