[package]
name = "olympus_tools_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "olympus_tools_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
cap-std = "2.0.0"