[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olympus-tools"
version = "0.1.0"
description = "Local tools: filesystem and HTTP with allow-lists"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = ["olympus_tools"]
